# Config format schema number
format_version: 4

debug: True
data_path: 'act/sample_data'
use_cache: True

num_workers: 0
batch_size: 4
lr: 0.0003
weight_decay: 0.0004
device: 'cpu'
data_usage: 4
pred_len: 90



